POST http://localhost:8080/api/v1/accounts
Content-Type: application/json
Authorization: bearer b128e970-518c-4b94-a7bb-6391580b480d

###

GET http://localhost:8080/api/v1/accounts/1
Accept: application/json

###

GET http://localhost:8080/api/v1/accounts
Accept: application/json

###

POST http://localhost:8080/api/v1/dispositions
Content-Type: application/json

{
  "funds": 10000,
  "accountNumber": "00000000000000000000000001",
  "operationName": "deposit"

}

###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

###

POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin&client_id=bank&grant_type=password

###

GET http://localhost:8080/api/v1/users/active
Accept: application/json
Authorization: bearer 0bd12394-81f2-4245-9241-ba8b24274d4e

###
